### ISSUE TITLE
autistic skid

### ISSUE THREAD

**Issue by 0x0403** [NotSwaraj/Proxyless-Nitrogen#2]
u fucking retard u skidded this off tear what a faggot

**Comment by Radu-wq** [comment]
Dude shut up, everyone knows Alex is an idiot.

**Comment by 0x0403** [comment]
> Dude shut up, everyone knows Alex is an idiot.

Radu nobody fucking loves you either

**Comment by NotSwaraj** [comment]
ahaha what a retard, if you didnt know, tear's gen is skidded lmao gtfo your more autistic + this one does use proxies

**Comment by NotSwaraj** [comment]
doesnt*

**Comment by 0x0403** [comment]
> ahaha what a retard, if you didnt know, tear's gen is skidded lmao gtfo your more autistic + this one does use proxies

no he didnt u autistic fuck kys tear is 100239402348234809234x smarter than all of you faggots

**Comment by NotSwaraj** [comment]
Ohh I see, your gay? Since you love tear so much, also wtf happend to his account. Is it you ?

**Comment by 0x0403** [comment]
> Ohh I see, your gay? Since you love tear so much, also wtf happend to his account. Is it you ?

shut the fuck up you are gay nigger his gf deleted it with all his other accounts on everything because shes a slut

**Comment by NotSwaraj** [comment]
he had a gf? Thats already pog 100 to him

**Comment by NotSwaraj** [comment]
What prompts you to call me a "nigger" why don't you go kys instead. Mind your own life sir (if you have 1 ofc which i highly doubt)

**Comment by 0x0403** [comment]
> What prompts you to call me a "nigger" why don't you go kys instead. Mind your own life sir (if you have 1 ofc which i highly doubt)

kys

**Comment by NotSwaraj** [comment]
lmao pussy why you close?
